# Generated by Django 3.1 on 2020-12-05 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_questionsnew_quiz_quizzcompletenew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsnew',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
        migrations.AlterModelOptions(
            name='quizzcompletenew',
            options={'verbose_name': 'Завершенные тесты', 'verbose_name_plural': 'Завершенные тесты'},
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='answer',
            field=models.CharField(help_text='Правильный вариант должен полностью повторять один из вариантов', max_length=100, verbose_name='Правильный вариант'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='option1',
            field=models.CharField(max_length=100, verbose_name='Вариант 1'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='option2',
            field=models.CharField(max_length=100, verbose_name='Вариант 2'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='option3',
            field=models.CharField(max_length=100, verbose_name='Вариант 3'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='option4',
            field=models.CharField(max_length=100, verbose_name='Вариант 4'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='question',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='questionsnew',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Викторина'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='quizzcompletenew',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Сдал?'),
        ),
        migrations.AlterField(
            model_name='quizzcompletenew',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='quizzcompletenew',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Викторина'),
        ),
        migrations.AlterField(
            model_name='quizzcompletenew',
            name='score',
            field=models.SmallIntegerField(verbose_name='Правильных ответов'),
        ),
        migrations.AlterField(
            model_name='quizzcompletenew',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
