# Generated by Django 3.1 on 2020-12-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201205_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-avatar.png', upload_to='profile_pics'),
        ),
    ]
